### ISSUE TITLE
Does it solve the react-native proxy issue

### ISSUE THREAD

**Issue by Obooman** [th317erd/rn-packager-proxy#1]
Hi,it seems that this repo aims to solve the remote debugger proxy issue,could you please add usage in README?

I should send you email for help but have no your email address,so I rise up an issue.

**Comment by th317erd** [comment]
This code is to intercept the RN packager websockets, to allow for the modification or redirection of the websocket connections from the packager.

**Comment by Obooman** [comment]
yes it's a proxy,I am not sure will this solve [this problem](https://github.com/facebook/react-native/issues/14758)?

**Comment by th317erd** [comment]
Possibly... I am not sure what the issue is (I remember having that problem, but I don't remember how I resolved it). This proxy will allow you to rewrite the contents of the code sent to the browser. I originally wrote it because the React team didn't allow you to modify port "8081" and I needed to, so this proxy will strip out that port number and replace it with a different one. Again, I am not sure this will solve your issue. I never gave a README because I wrote this as a quick hack for myself. You can read the code though, it is very simple.

**Comment by Obooman** [comment]
Sadly it seems that this is not the solution.When you find out how you solve this please let me know or [email me](mailto://oboochin@gmail.com).such a painful problem😞.AND,thanks for your patient!
